### ISSUE TITLE
Allow listing usage in API

### ISSUE THREAD

**Issue by hderms** [bkirwi/decline#177]
I have a use case where I want to throw an exception (in order to fail an IO) if a particular flag isn't set in a particular context. I want that exception to contain information about how to turn the flag on i.e.
`new Exception(s"Failed to Foo, turn on ${Usage.fromOpt(BarOption)}` 

with the intention that the string look something like `Failed to Foo, turn on --bar`. For now I'm using the `toString` method, but it's output isn't exactly what I want: `Opts([--rewrite]` . Usage itself is private to the module, so I can't really work around this.

I understand why making Usage private to the module would help hide implementation details, but some mechanism of printing `--rewrite` seems generally useful to the end-user

**Comment by bkirwi** [comment]
Interesting! I think the big challenge with this sort of thing is that it has to make sense for all `Opts` instances, even the really complicated ones. For example, the usage slug in your example is `[--rewrite]`, with the square brackets expressing that it's optional. (Maybe because you added a default value or some such thing.) I suspect you just want the `--rewrite` string for your error message... but then what do we do for composite `Opts`?

I don't know if this matches your case, but I should mention it for any future readers: it's often best if you can express whatever constraints you have in the way you build your opts. So say you want `--rewrite` to be passed iff `--mode <mode>` is passed as well, you might have:

```scala
val rewrite = Opts.flag("rewrite", ...)
val mode = Opts.option[Mode]("mode", ...)
val rewriteMode = (rewrite, mode).mapN((_, _) => ...).orNone
```

...which will parse if both are provided, or neither are. Definitely endorse trying to push constraints into the structure if you can... better error messages, better help text, validation for free, etc.

**Comment by hderms** [comment]
@bkirwi we can't push it into the type structure very easily because it's based on information at runtime. More specifically in our case, you have to pass the rewrite flag if the directory already exists

**Comment by bkirwi** [comment]
Hey -- going through old issues, and I think this is something that unfortunately there's not a great way to support. Some rationale:
- `Usage.fromOpt` doesn't even return quite what you'd want for this case, since it's wrapped up in square brackets to express that it's optional... very useful in the normal context, but unfortunately not in yours!
- There's no good way to expose a "just get the underlying flag name" method, since any method we stick on `Opts` has to work for all cases, even the very composite ones.
- It's not too awkward to deal with at another level -- a `val BarOptionName = "bar"` constant somewhere can help keep these things in sync.

You could imagine restructuring the public API to expose a different trait for singular options that we could hang such a method off of... but once you chase all those changes through, the shape of the library ends up being quite different.

I appreciate that this is not the sort of answer one hopes for when opening an issue! Appreciate the suggestions and feedback nonetheless.
