### ISSUE TITLE
Publishing a version that uses cats-core 2.2.0

### ISSUE THREAD

**Issue by pfvalter** [bkirwi/decline#238]
Hey there. Considering that the work was done 5 months ago now. Can we get a release of decline that uses those versions? Thanks in advance.

**Comment by bkirwi** [comment]
I should be able to cut a release in the next day or so, sure. (It'll probably go out for cats 2.4.x, since that's the latest.)

Note that the current release is compatible with cats 2.2.0, though, since the 2 series has kept compatibility throughout. You should be able to use the current 1.3.0 artifact with any 2.x-series cats.

**Comment by bkirwi** [comment]
Just pushed a release `1.4.0` that bumps us up to recent cats - 2.4.1. Enjoy!
