### ISSUE TITLE
validate arguments against each other

### ISSUE THREAD

**Issue by ttj4** [bkirwi/decline#332]
```
  val minIdCOpt = Opts.option[Long](long = "min-id", short = "m", metavar = "Min ID", help = "Min ID").withDefault(1L)
  val maxIdCOpt = Opts.option[Long](long = "max-id", short = "x", metavar = "Max ID", help = "Max ID(min < max)")
```

is it possible to validate max > min? 

like  
```
Opts.option[Long](long = "max-id", short = "x", metavar = "Max ID", help = "Max ID(min < max)").validate("check min vs max) {
 _some operation_
}
```

**Comment by bkirwi** [comment]
yep! the idea is to compose them first, and then validate the result. something like:

```scala
minIdCOpt, maxIdCOpt).tupled.validate("min < max") { case (min, max) => min < max}
```

since you're presumably composing those two options somewhere in your program already, there's often a good existing place to insert a validation like that. but hard to say for sure without a look at more of the program.

**Comment by bkirwi** [comment]
Closing, but feel free to reopen if you have any more questions!

**Comment by ttj4** [comment]
this is helpful, thank you!
