### ISSUE TITLE
Requesting `--help` should not return same exit status as not requesting help

### ISSUE THREAD

**Issue by adamretter** [bkirwi/decline#452]
Hi there, I very much like decline, so thank you :-)
I do think there could be a small problem with an assumption around exit codes made by decline. So I thought I would ask here...

Given the following example from your docs:

```scala
def main(args: Array[String]) = tailCommand.parse(args, sys.env) match {
  case Left(help) =>
    System.err.println(help)
    sys.exit(1)
  case Right(parsedValue) =>
    // Your program goes here!
}
```

I cannot determine the difference between invoking `myapp --help` (which is a valid command) or just `myapp` (where some mandatory arguments are missing).

I have checked this against some linux utilities, and it seems that the convention I have seen is that:
* `myapp --help` is a valid code and should print to stdout, and then return exit code 0
* `myapp` where there are missing mandatory arguments, could print an error (and/or help message) to stderr, and then return exit code 1.

It seems to me that to follow this convention we would need the decline API to make the help in the Left of the disjunction a bit more informative as to whether the user specified the `--help` flag or not, e.g. something more like:

```scala
case class Help(requested: Boolean, text: String)

...

def main(args: Array[String]) = tailCommand.parse(args, sys.env) match {
  case Left(help: Help) if help.requested =>
    println(help.text)
    sys.exit(0)
  case Left(help: Help) =>
    System.err.println("Missing required mandatory arguments")
    System.err.println(help.text)
    sys.exit(1)
  case Right(parsedValue) =>
    // Your program goes here!
}
```

Any thoughts on this please?

**Comment by bkirwi** [comment]
Happily this info is already available via the API, if slightly indirectly!
The `Help` case class includes a list of errors -- since it needs to be
able to print them -- so it would suffice to replace your `help.requested`
with `help.errors.isEmpty`. (In general it's safer to check whether there
were any errors than whether the help flag was specified, in case eg. they
specified other flags that cause a parse error.)

I'd be open to merging a helper method that gave users a more intuitive
shorthand for `errors.isEmpty`, and/or pointing out this option in the
docs. I think it's a bit late to change CommandApp and friends, though, at
least before the next major release.

(Not the point of your example, but printing "Missing required mandatory
arguments" there is not quite right... `decline` can produce a wide variety
of helpful errors that aren't just missing-required-options. Best to let
the errors speak for themselves.)

**Comment by bkirwi** [comment]
Oh, and I should say: glad you're enjoying `decline`, and thanks for doing the legwork of checking out existing precedent etc. before posting your suggestion!

**Comment by adamretter** [comment]
@bkirwi Thanks, that is great news :-)

I would be happy to submit a PR to improve the docs if you like?

**Comment by bkirwi** [comment]
Certainly! I think a fine place would be as part of, or near, the example `main` method near the bottom.
