### ISSUE TITLE
Composing subcommands 

### ISSUE THREAD

**Issue by BenHutchisonSeek** [bkirwi/decline#64]
Decline provides the `product` combinator to compose multiple subcommands in a row, but it appears the parser has an internal assumption that there will be just one subcommand. 

In this example, we construct a Opts for two parallel subcommands, but the parser is unable to parse the corresponding input.

```
Welcome to the Ammonite Repl 1.4.2
(Scala 2.12.7 Java 11.0.1)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`com.monovore:decline_2.12:0.6.2`
import $ivy.$

@ import cats.implicits._
import cats.implicits._

@ import com.monovore.decline._
import com.monovore.decline._

@ import cats._
import cats._

@ val nel = Apply[Opts].product(Opts.subcommand("FooInt", "fint")(Opts.argument[Int]("n")), Opts.subcommand("FooS", "foos")(Opts.argument[String]("s")))
nel: Opts[(Int, String)] = App(
  App(Pure(cats.Apply$$Lambda$1767/0x0000000800a07040@636e4bf8), Subcommand(com.monovore.decline.Command@302da330)),
  Subcommand(com.monovore.decline.Command@3568ea59)
)

@ val cmd = Command("test", "test")(nel)
cmd: Command[(Int, String)] = com.monovore.decline.Command@30bd39d5

@ cmd.parse(List("FooInt", "6", "FooS", "s" ))
res6: Either[Help, (Int, String)] = Left(
  Help(
    List("Unexpected argument: FooS"),
    NonEmptyList("test", List("FooInt")),
    List("<n>"),
    List(
      "fint",
      """Options and flags:
    --help
        Display this help text."""
    )
  )
)
```

It seems like there is an assumption in the [parser logic](https://github.com/bkirwi/decline/blob/master/core/shared/src/main/scala/com/monovore/decline/Parser.scala#L82) that there is just one subcommand, although the `Opts` algebra seems to allow it.

**Comment by bkirwi** [comment]
Hey, sorry to let this one hang for so long -- I had a reply all typed up, but it seems I lost it! The same thing in bullet form:
- Indeed -- the parser's is restricted to one subcommand per nesting level. This the standard subcommand idiom -- ie. you can run `git submodule add` (a nested subcommand) but not `git status commit` (two top-level subcommands).
- It's lame that you can build a parser that "expects" two subcommands "at once", even though a user can specify at most one. This is a hazard of making `subcommand` just another `Opts`, because the algebra effectively _forces_ you to allow it. The benefits outweigh the costs, but the costs are definitely real.
- One thing we _can_ do is to improve the error message here. Ideally, you'd want the error to tell you that passing both `FooS` and `FooInt` is impossible. The changes in the parser would need to be a) when we find a subcommand, report other errors in the parser before moving into the subcommand, and b) special case the "missing subcommand" error in that context, to make it clear that the error is in the parser and not the input to it.
- If you want to share a bit more about the logic you're trying to capture, I'd be happy to try and figure out if there's another way to express that in `decline`.

**Comment by mslinn** [comment]
[Here are the docs](http://cadenza.micronauticsresearch.com/man/man1/cad.1.html) that describe the many subcommands we need to implement. [Here is more info](http://cadenza.micronauticsresearch.com/man/man1/cad-curriculum.1.html#action_options) on some of the subcommands. Is it true that Decline cannot be used to implement these subcommands?

**Comment by bkirwi** [comment]
`decline` absolutely can be used for that! Multiple subcommands are usually composed with `orElse`, as discussed here: http://ben.kirw.in/decline/usage.html#commands-and-subcommands. So in your case you'd have something like:

```scala
val adminCommand = Opts.subcommand("admin", "Provides administrative functionality.") { ... }
val courseCommand = Opts.subcommand("course", "Builds a [...]") { ... }
...

val eitherCommand = adminCommand orElse courseCommand orElse ...
```
It also supports nested subcommands, so you can also do

```scala
val adminCommand = Opts.subcommand("admin", "Provides administrative functionality.") { 
  Opts.subcommand("db", "...") { ... }
}
```

This issue is looking for something different: in the code example above is looking for a third behaviour, where multiple non-nested subcommands are invoked "at once." It's not really how subcommands normally work, and it's not supported here.

Offhand: those are lovely man pages! Do you use a tool for that?

**Comment by mslinn** [comment]
Thanks for the info, I'll give it a try.

I used [Pandoc](https://pandoc.org/) and some Lua scripts to make the man pages in multiple output formats, including man format and HTML.

**Comment by mslinn** [comment]
@bkirwi I put together a [GitHub project (`decline-test`)](https://github.com/mslinn/decline-test/blob/master/src/main/scala/Cad.scala) to try out `decline` on the command syntax described in my man pages. A few questions came up, so I included them as comments in the program. Would you mind taking a look, and responding to the questions in `decline-test`?

**Comment by bkirwi** [comment]
Left a few notes here: https://github.com/mslinn/decline-test/issues/1

I think the refined issues seem to be with refined itself, so I don't have much to say there.
