### ISSUE TITLE
Add withDefault value to help message

### ISSUE THREAD

**Issue by taig** [bkirwi/decline#65]
When using `Opts.withDefault` I would expect the given value to appear in the help message. Unfortunately it does not and it is not impossible to add it to an existing `Opts`.

```scala
val maxConcurrent: Opts[Int] =
  Opts.option[Int]("max-concurrent", "Maximum amount of concurrent connections")

val maxConcurrentOrDefault: Opts[Int] = maxConcurrent.withDefault(4)
```

Ideally I'd wish for a way to modify the help message of an existing `Opts`. E.g. something like:

```scala
val maxConcurrentOrDefault: Opts[Int] = {
  val default = 4
  maxConcurrent.withDefault(default).updateHelp(_ + s" [default: $default]")
}
```

**Comment by bkirwi** [comment]
Hmm, interesting! Definitely see the appeal, but may be tricky to execute
well.

Do you know any examples of popular unix command-line tools that format
their help in the way you're suggesting?

**Comment by Taig** [comment]
Good point. In fact, now that I'm actively looking for it, I don't seem to find much. There is [docopt](http://docopt.org/) wich suggests:

> If you want to set a default value for an option with an argument, put it into the option's description, in the form [default: \<the-default-value\>].

Looking around in my terminal, I discovered `docker` using another format:

```
Options:
  -a, --all-tags                Download all tagged images in the repository
      --disable-content-trust   Skip image verification (default true)
```

All in all this seems to be a narrow use case. I don't mind if we close this issue for this reason, I can get along with my own `Opts` wrapper for this purpose.

**Comment by bkirwi** [comment]
Cool, thanks for poking around. My (limited) checks don't show much standard either for showing this information, unfortunately.

The other tricky bit: for this to be a method on `Opts`, you'd need to support it on composite instances as well. So eg. `(optsA, optsB).tupled.updateHelp(_ + "whatever")` would need to be legal too. Easy enough to support -- the obvious implementation would be to update the help text of all relevant options -- but a bit weird? You could also take the route of baking it in to the options themselves -- `Opts.option[Int]("whatever", help = "Hi!", default = Some(7))` which might not be the worst thing, but is sort of invasive / redundant, and you'd need to change `Argument` to require a formatter for values and not just a parser. (You'd still want the `withDefault` method on `Opts`, because it's more flexible.)

I wouldn't totally rule out such a change -- making the help text more helpful is something this lib really cares about -- but I'm not super eager given the cost. I'll leave this one open for now.

**Comment by antonkulaga** [comment]
Very useful feature! It is very annoying to each time manually tell the user default values in withDefault settings and sometimes you change the default and forget about to change help if there would be a way to automatically include defaults to help it will prevent many potential bugs

**Comment by bkirwi** [comment]
I'm closing this one out, since:
- Tricky to solve in a general-purpose way in `decline`, as mentioned above... possibly defaults need to be formattable, nonobvious behaviour for composite `Opts`, etc.
- Not that awkward to solve in user code, with the sort of helpers like taig mentions.
- There's no standard way to format this stuff. (And so far `decline` has worked fairly hard to include just things that are standardized or extremely common.)

Appreciate the suggestion and the discussion, though!
